# Generated by Django 5.1.6 on 2025-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "banner_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("banner_link", models.URLField(blank=True, null=True)),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="banner_images/"
                    ),
                ),
                (
                    "banner_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Home Banner 640x926", "Home Banner 640x926"),
                            ("Home Banner 2496x300", "Home Banner 2496x300"),
                            (
                                "News Article Banner 600x700",
                                "News Article Banner 600x700",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
