# Generated by Django 5.1.6 on 2025-05-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsTagBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_name", models.CharField(blank=True, max_length=100, null=True)),
                ("news_link", models.URLField(blank=True, null=True, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
