# Generated by Django 4.2.18 on 2025-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akp_news', '0002_advertisements'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveupdates',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
