# Generated by Django 4.2.18 on 2025-06-28 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akp_news', '0003_liveupdates_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdates',
            name='slug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_updates', to='akp_news.news'),
        ),
    ]
