# Generated by Django 5.1.6 on 2025-05-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0003_news_meta_description_news_meta_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="news",
            name="meta_image",
        ),
        migrations.RemoveField(
            model_name="news",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="news",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="newscategory",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="newscategory",
            name="meta_image",
        ),
        migrations.RemoveField(
            model_name="newscategory",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="newscategory",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="newscomment",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="newscomment",
            name="meta_image",
        ),
        migrations.RemoveField(
            model_name="newscomment",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="newscomment",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="newstag",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="newstag",
            name="meta_image",
        ),
        migrations.RemoveField(
            model_name="newstag",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="newstag",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="newstagbanner",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="newstagbanner",
            name="meta_image",
        ),
        migrations.RemoveField(
            model_name="newstagbanner",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="newstagbanner",
            name="meta_title",
        ),
        migrations.AlterField(
            model_name="news",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="newscategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="newscomment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="newstag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="newstagbanner",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
