# Generated by Django 5.1.6 on 2025-05-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0005_newshomebanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newshomebanner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="newstagbanner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
