# Generated by Django 5.2.4 on 2025-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akp_news', '0005_aboutus_newssubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['order'], 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AddField(
            model_name='newscategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
