# Generated by Django 5.2.4 on 2025-08-06 02:31

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akp_news', '0006_alter_aboutus_options_alter_newscategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['-order'], 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AddField(
            model_name='news',
            name='featured_video',
            field=models.CharField(blank=True, help_text='YouTube or Vimeo link for featured video (Recommended Link Format: VIDEO_ID Only)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(help_text='Author of the article', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(help_text='Category of the article', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='akp_news.newscategory'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Content of the article.', null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for this article (Recommended size: 16:9)', null=True, upload_to='news_images_v2/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(help_text="Unique URL slug for the article. Use only alphanumeric characters, underscores, and hyphens. Example: 'my-article-title'.", max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, help_text='Short summary of the article (max 200 characters)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with the article', related_name='news', to='akp_news.newstag'),
        ),
    ]
