# Generated by Django 5.2.4 on 2025-08-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akp_news', '0007_alter_newscategory_options_news_featured_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory of the article', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='akp_news.newssubcategory'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the article', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='akp_news.newscategory'),
        ),
    ]
