# Generated by Django 5.1.6 on 2025-05-13 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0008_remove_news_view_count_viewcountnews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="viewcountnews",
            name="impressions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="viewcountnews",
            name="total_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="viewcountnews",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="viewcountnews",
            unique_together={("news", "ip_addr")},
        ),
    ]
