# Generated by Django 5.1.6 on 2025-05-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "akp_news",
            "0009_viewcountnews_impressions_viewcountnews_total_clicks_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Live Updates",
            },
        ),
    ]
