# Generated by Django 5.1.6 on 2025-05-14 02:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0010_liveupdates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
