# Generated by Django 5.1.6 on 2025-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0012_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="banner_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
