# Generated by Django 5.1.6 on 2025-06-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_news", "0015_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialaccount",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
