# Generated by Django 5.1.6 on 2025-06-12 13:42

import Base.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Epaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=Base.base.generate_uuid_hex,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                (
                    "meta_image",
                    models.ImageField(blank=True, null=True, upload_to="meta_images"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="epapers/")),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "E-Papers",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EpaperDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ip_addr", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epapers_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epaper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="akp_epapers.epaper",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "E-Paper Downloads",
            },
        ),
    ]
