# Generated by Django 5.1.6 on 2025-06-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("akp_epapers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epaperdownload",
            name="downloads_limit",
        ),
    ]
