# Generated by Django 5.1.6 on 2025-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_epapers", "0002_remove_epaperdownload_downloads_limit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epaper",
            options={"ordering": ["-timestamp"], "verbose_name_plural": "E-Papers"},
        ),
        migrations.AddField(
            model_name="epaper",
            name="timestamp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
