# Generated by Django 5.1.6 on 2025-07-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("akp_epapers", "0002_epaper_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="epaper",
            name="thumbnail",
        ),
    ]
