# Generated by Django 5.1.6 on 2025-07-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_epapers", "0003_remove_epaper_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_url", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "epaper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="short_url",
                        to="akp_epapers.epaper",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Short URLs",
            },
        ),
    ]
