# Generated by Django 5.1.6 on 2025-07-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_epapers", "0004_shorturl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_url",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
