# Generated by Django 5.2.4 on 2025-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akp_epapers', '0005_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epaper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='akp_epapers/pdfs/'),
        ),
    ]
