# Generated by Django 5.2.4 on 2025-08-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akp_epapers', '0007_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
