# Generated by Django 5.1.6 on 2025-06-03 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("akp_accounts", "0002_customuser_epaper_downloads"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username_attempt",
                    models.CharField(
                        help_text="The username attempted to log in", max_length=255
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED_CREDENTIALS", "Failed - Wrong Credentials"),
                            (
                                "FAILED_CONCURRENT_LIMIT",
                                "Failed - Concurrent Limit Reached",
                            ),
                            ("FAILED_NOT_STAFF", "Failed - Not a Staff Account"),
                            ("FAILED_OTHER", "Failed - Other Reason"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Details if the login failed.", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user account if the username matched an existing staff user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Login Attempt",
                "verbose_name_plural": "Admin Login Attempts",
                "ordering": ["-timestamp"],
            },
        ),
    ]
