# Generated by Django 4.2.18 on 2025-06-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akp_accounts', '0002_customuser_is_user_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_otp',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
