# Generated by Django 5.2.4 on 2025-07-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover Image. Recommended size: 600x1200px. Portrait Image.', null=True, upload_to='webstories/cover_images/'),
        ),
    ]
