# Generated by Django 5.2.4 on 2025-08-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0002_alter_webstory_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover Image. Recommended size: 600x800px. Portrait Image.', null=True, upload_to='webstories_v2/cover_images/'),
        ),
        migrations.AlterField(
            model_name='webstoryslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the slide. Recommended size: 600x800px.', null=True, upload_to='webstories_v2/slides/'),
        ),
    ]
