# Generated by Django 5.2.4 on 2025-08-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0003_alter_webstory_cover_image_alter_webstoryslide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstoryslide',
            name='caption',
            field=models.TextField(blank=True, help_text='Caption text overlay for the slide. Recommended length: 150-170 characters.', null=True),
        ),
    ]
