# Generated by Django 5.2.4 on 2025-08-08 11:47

import webstories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0004_alter_webstoryslide_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='slug',
            field=models.SlugField(default=webstories.models.get_short_id, max_length=20),
        ),
    ]
