# Generated by Django 5.2.4 on 2025-08-08 13:31

import webstories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0005_alter_webstory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstory',
            name='slug',
            field=models.SlugField(default=webstories.models.get_short_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='webstoryslide',
            name='caption',
            field=models.TextField(blank=True, help_text='Caption text overlay for the slide. Recommended length: 170-200 characters.', null=True),
        ),
    ]
